export const STEP_ACTION_TYPES = {
  HAD_NEXT: 'HAD_NEXT',
  HAD_PREV: 'HAD_PREV',
  CHANGED: 'CHANGED',
}

export const FORM_ACTION_TYPES = {
  SUBMITTED: 'SUBMITTED',
  SUCCESSED: 'SUCCESSED',
  TYPED: 'TYPED',
}
